//Partially generated by ChatGPT
document.addEventListener("DOMContentLoaded", () => {
    const cards = document.querySelectorAll(".skill-card");

    cards.forEach(card => {
        card.addEventListener("click", () => {
            const title = card.querySelector("h3").textContent;
            const price = card.querySelector(".price").textContent;
            const provider = card.querySelector(".provider").textContent;

            alert(`${title}\n${price}\n${provider}`);
        });
    });
});